name: Terraform CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:   # lets you kick it off manually

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.ACTIONS_ROLE_ARN }}
          aws-region:     us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Init
        working-directory: infra/terraform
        run: terraform init

      - name: Plan
        working-directory: infra/terraform
        run: terraform plan

      - name: Apply
        if: github.ref == 'refs/heads/main'
        working-directory: infra/terraform
        run: terraform apply -auto-approve
